spring.datasource.url=jdbc:mysql://localhost:3306/clientmanagmentsystem_db
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=truespring.application.name=clientmanagmentsystem
